name: Batch check of latexindent.pl
on:
  push:

jobs:
  latexindent-batch-check:
    # run latexindent on each tex file and diff the result with committed file. Produces failure of the formatting is not applied properly.
    name: running latexindent.pl --check on files in test-cases/check-switch-tests/
    runs-on: [ubuntu-latest]
    steps:
      # checkout github.com/cmhughes/latexindent.pl
      #
      # https://github.com/actions/checkout
      - name: Loading the "base actions/checkout" so as to access latexindent.pl
        uses: actions/checkout@v2
      - name: installing Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'
      - name: installing perl modules for latexindent.pl
        run: |
          cpanm YAML::Tiny
          cpanm File::HomeDir
          cpanm Unicode::GCString
      - name: the loop for running latexindent.pl --check on files in test-cases/check-switch-tests/
        run: |
          for file in test-cases/check-switch-tests/*.tex
          do
             perl latexindent.pl --check $file
          done
