name: Batch check of latexindent.pl
on:
  push:

jobs:
  latexindent-batch-check:
    # run 
    #   latexindent --check 
    # on each .tex file within test-cases/check-switch-tests
    #
    # Process will fail if indented text is different from file
    name: latexindent.pl --check on test-cases/check-switch-tests/*.tex (${{ matrix.platform }}, Perl ${{ matrix.perl }})
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        perl: [ '5.34', '5.32', '5.30' ]
    runs-on: ${{ matrix.platform }}
    steps:
      # checkout github.com/cmhughes/latexindent.pl
      #
      # https://github.com/actions/checkout
      - name: Loading the "base actions/checkout" so as to access latexindent.pl
        uses: actions/checkout@v2
      - name: installing Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: installing perl modules for latexindent.pl
        run: |
          cpanm YAML::Tiny
          cpanm File::HomeDir
          cpanm Unicode::GCString
      - name: loop for running latexindent.pl --check test-cases/check-switch-tests/*.tex
        run: |
          for file in test-cases/check-switch-tests/*.tex
          do
             perl latexindent.pl --check -s $file && echo "latexindent.pl check passed for $file (file unchanged by latexindent.pl)"
          done
  latexindent-batch-check-windows:
    name: latexindent.pl --check on test-cases/check-switch-tests/*.tex (WINDOWS, Perl ${{ matrix.perl }})
    strategy:
      matrix:
        platform: [windows-latest]
        perl: ['5.32', '5.30' ]
    steps:
      # checkout github.com/cmhughes/latexindent.pl
      #
      # https://github.com/actions/checkout
      - name: Loading the "base actions/checkout" so as to access latexindent.pl
        uses: actions/checkout@v2
      - name: installing Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          distribution: strawberry
      - name: installing perl modules for latexindent.pl
        run: |
          cpanm YAML::Tiny
          cpanm File::HomeDir
          cpanm Unicode::GCString
      - name: loop for running latexindent.pl --check test-cases/check-switch-tests/*.tex
        run: for %%f in (directory\path\*) do perl latexindent.pl --check -s %%f
