name: Batch check of latexindent.pl
on:
  push:

jobs:
  list_tex_files:
    # list all .tex files in this repo and save them in a variable that can be used by other jobs as input for their matrix (so they run one job on each tex file)
    outputs:
      matrix: ${{ steps.list-files.outputs.matrix }}
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: list .tex files in test-cases/check-switch-tests
        id: list-files
        # print each filename (relative path) as an element of a JSON list, github can parse this into setting output variable "matrix"
        run: |
          cd test-cases/check-switch-tests
          printf "::set-output name=matrix::{\"include\":["
          find . -name "*.tex" -exec printf "{\"file\":\"{}\"}," \;
          printf "]}\n"
  check_formatting:
    # run latexindent on each tex file and diff the result with committed file. Produces failure of the formatting is not applied properly.
    needs: [list_tex_files]
    runs-on: [ubuntu-latest]
    strategy:
      matrix: ${{fromJson(needs.list_tex_files.outputs.matrix)}}
      fail-fast: false
    steps:
      # checkout github.com/cmhughes/latexindent.pl
      #
      # https://github.com/actions/checkout
      - name: Loading the "base actions/checkout" so as to access latexindent.pl
        uses: actions/checkout@v2
      - name: installing Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'
      - name: installing perl modules for latexindent.pl
        run: |
          cpanm YAML::Tiny
          cpanm File::HomeDir
          cpanm Unicode::GCString
      - name: running latexindent.pl --check ${{ matrix.file }}
        run: |
          cd test-cases/check-switch-tests
          perl latexindent.pl --check ${{ matrix.file }}
