name: Build and publish latexindent executables and documentation to releases
# PURPOSE:
#
#  1. build documentation latexindent.pdf 
#  2. build Windows latexindent.exe using PAR::Packer on Strawberry Perl, and publish to the most recent tag (release)
#  3. build Linux latexindent executable using PAR::Packer, and publish to the most recent tag (release)
#  4. build MacOS latexindent executable using PAR::Packer, and publish to the most recent tag (release)
#  5. create latexindent.zip, and publish latexindent.zip to the most recent tag (release)
#
# Note: this action only runs on *each release*, i.e. when tags are pushed
#

on:
  push:
    tags:
      - '*'

jobs:
  #-------------------------------------------------------------------------------------
  #
  # latexindent.pdf
  #
  build-latexindent-doc-pdf:
    name: 'build documentation latexindent.pdf'
    runs-on: ubuntu-latest
    steps:
      - name: load the "base actions/checkout" so as to access latexindent.pl
        uses: actions/checkout@v3
      - name: installing texlive full
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            github_sha_short=$(echo $GITHUB_SHA | cut -c1-7)
            github_branch="main"
            github_release=$(echo ${{ github.ref }}|cut -d'/' -f 3)
            sed -i.bak s/\\\\gitAbbrevHash/$github_sha_short/ documentation/latexindent.tex
            sed -i.bak s/\\\\gitBranch/main/ documentation/latexindent.tex
            sed -i.bak s/\\\\gitRel/$github_release/ documentation/*.tex
            sed -i.bak "s|\\\\gitAuthorDate|$(date +'%Y-%m-%d')|g" documentation/latexindent.tex
      - name: pdflatex compilation
        run: |
            cd documentation
            pdflatex --interaction=batchmode latexindent
            makeindex -s latexindent.ist -t latexindent.ilg latexindent.idx -o latexindent.ind
            bibtex latexindent
            pdflatex --interaction=batchmode latexindent
            pdflatex --interaction=batchmode latexindent
            pdflatex --interaction=batchmode latexindent
      - name: move latexindent.pdf to release directory
        run: |
            cd ..
            mkdir -p target/release
            mv documentation/latexindent.pdf target/release
      #
      # https://stackoverflow.com/questions/57498605/github-actions-share-workspace-artifacts-between-jobs
      #
      - name: upload latexindent.pdf as artifact for zipping
        uses: actions/upload-artifact@master
        with:
          name: latexindent.pdf
          path: target/release
  zip-files:
    name: 'create latexindent.zip and upload to release'
    needs: [build-latexindent-doc-pdf]
    runs-on: ubuntu-latest
    steps:
      - name: Loading the "base actions/checkout" so as to access the repository latexindent.pl
        uses: actions/checkout@v3
      - name: graphical representation of latexindent directory
        run: |
          find latexindent -print | sed -e 's;[^/]*/;|-- ;g;s;-- |; |;g'
      #
      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      #
      - name: upload latexindent.zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: latexindent.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "latexindent.pl release txt"
