name: build latexindent executables and documentation and upload to release page
# PURPOSE:
#
#  1. build latexindent.pdf 
#  2. build latexindent.exe using PAR::Packer on Strawberry Perl
#  3. build latexindent-linux using PAR::Packer on Ubuntu
#  4. build latexindent-macos using PAR::Packer on macOS
#  5. create and release latexindent.zip
#  6. upload latexindent.zip to ctan   
#
# Note: this action only runs on *each release*, i.e. when tags are pushed
#

on:
  push:
    tags:
      - '*'

jobs:
  #-------------------------------------------------------------------------
  #
  # latexindent.pdf
  #
  build-latexindent-doc-pdf:
    name: 'documentation latexindent.pdf creation'
    runs-on: ubuntu-latest
    steps:
      - name: load the "base actions/checkout" so as to access latexindent.pl
        uses: actions/checkout@v3
      - name: DUMMY create latexindent.pdf
        run: |
          mkdir -p target/release
          cp documentation/latexindent.tex target/release/latexindent.pdf
      #
      # https://stackoverflow.com/questions/57498605/github-actions-share-workspace-artifacts-between-jobs
      #
      - name: upload latexindent.pdf as artifact for zipping
        uses: actions/upload-artifact@master
        with:
          name: latexindent.pdf
          path: target/release
  #-------------------------------------------------------------------------
  #
  # latexindent.exe
  #
  build-windows-exe:
    name: 'create Windows executable latexindent.exe using Strawberry Perl 5.32 on Windows'
    runs-on: ubuntu-latest
    steps:
      - name: load the "base actions/checkout" so as to access latexindent.pl
        uses: actions/checkout@v3
      - name: DUMMY create latexindent.pdf
        run: |
          mkdir -p target/release
          cp documentation/latexindent.tex target/release/latexindent.exe
      #
      # https://stackoverflow.com/questions/57498605/github-actions-share-workspace-artifacts-between-jobs
      #
      - name: upload latexindent.pdf as artifact for zipping
        uses: actions/upload-artifact@master
        with:
          name: latexindent.exe
          path: target/release
  #-------------------------------------------------------------------------
  #
  # Linux latexindent
  #
  build-linux-executable:
    name: 'create Linux executable latexindent'
    runs-on: ubuntu-latest
    steps:
      - name: load the "base actions/checkout" so as to access latexindent.pl
        uses: actions/checkout@v3
      - name: DUMMY create latexindent.pdf
        run: |
          mkdir -p target/release
          cp documentation/latexindent.tex target/release/latexindent-linux
      #
      # https://stackoverflow.com/questions/57498605/github-actions-share-workspace-artifacts-between-jobs
      #
      - name: upload latexindent-linux as artifact for zipping
        uses: actions/upload-artifact@master
        with:
          name: latexindent-linux
          path: target/release
  #-------------------------------------------------------------------------
  #
  # MacOS latexindent
  #
  build-macos-executable:
    name: 'create MacOS executable latexindent'
    runs-on: ubuntu-latest
    steps:
      - name: load the "base actions/checkout" so as to access latexindent.pl
        uses: actions/checkout@v3
      - name: DUMMY create latexindent.pdf
        run: |
          mkdir -p target/release
          cp documentation/latexindent.tex target/release/latexindent-macos
      #
      # https://stackoverflow.com/questions/57498605/github-actions-share-workspace-artifacts-between-jobs
      #
      - name: upload latexindent-linux as artifact for zipping
        uses: actions/upload-artifact@master
        with:
          name: latexindent-macos
          path: target/release
  #=========================================================================
  #
  # latexindent.zip
  #
  zip-files:
    name: 'create latexindent.zip and uploading to release'
    needs: [build-latexindent-doc-pdf, build-windows-exe, build-linux-executable, build-macos-executable]
    runs-on: ubuntu-latest
    steps:
      - name: Loading the "base actions/checkout" so as to access the repository latexindent.pl
        uses: actions/checkout@v3
      - name: copy source files from repository into temporary folder
        run: |
          mkdir latexindent
          cp latexindent.pl latexindent/
          cp defaultSettings.yaml latexindent/
          mkdir latexindent/LatexIndent/
          cp LatexIndent/*.pm latexindent/LatexIndent/
          cp helper-scripts/latexindent-module-installer.pl latexindent/
          mkdir latexindent/bin/
          mkdir latexindent/bin/windows
          mkdir latexindent/bin/linux
          mkdir latexindent/bin/macos
      - name: copy documentation files from repository into temporary folder
        run: |
          mkdir latexindent/documentation/
          cp documentation/latexindent.tex latexindent/documentation/
      - name: download all artifacts
        uses: actions/download-artifact@master
        with:
          path: latexindent-binaries
      - name: create latexindent.zip
        run: |
          mv latexindent-binaries/latexindent.exe latexindent/bin/windows
          mv latexindent-binaries/latexindent-linux latexindent/bin/linux/latexindent
          mv latexindent-binaries/latexindent-macos latexindent/bin/macos/latexindent
          mv latexindent-binaries/latexindent.pdf latexindent/documentation/
          zip -r latexindent.zip latexindent/
          mkdir -p target/release
          cp latexindent.zip target/release
      - name: upload latexindent.zip as artifact
        uses: actions/upload-artifact@master
        with:
          name: latexindent.zip
          path: target/release
      - name: graphical representation of latexindent directory
        run: |
          find latexindent -print | sed -e 's;[^/]*/;|-- ;g;s;-- |; |;g'
      - name: get changelog.md information
        id: changelog
        run: |
          csplit documentation/changelog.md '/^\#\#/' '{*}' -f cmh # split changelog at '##'
          sed -i.bak s/\#\#.*\// cmh01                             # 
          mv cmh01 target/release/latexindent-release.md
      - name: upload latexindent-release.md as artifact
        uses: actions/upload-artifact@master
        with:
          name: latexindent-release.md
          path: target/release
  #=========================================================================
  #
  # create release
  #
  create-release:
    name: 'latexindent create release'
    runs-on: ubuntu-latest
    needs: [zip-files]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: download all artifacts
        uses: actions/download-artifact@master
        with:
          run: |-
             echo "before"
             ls -l
             mv latexindent.zip/latexindent.zip latexindent.zip
             mv latexindent.exe/latexindent.exe latexindent.exe
             mv latexindent-linux/latexindent-linux latexindent-linux
             mv latexindent-macos/latexindent-macos latexindent-macos
             echo "after"
             ls -l
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: latexindent-release.md
          files: |
            latexindent.zip
            latexindent.exe
            latexindent-linux
            latexindent-macos
  #=========================================================================
  #
  # ctan latexindent.zip upload
  #
  ctan-upload:
    name: 'upload latexindent.zip to ctan'
    runs-on: ubuntu-latest
    needs: [zip-files]
    steps:
      - name: get latexindent version number
        id: labeller
        run: |
          echo "version=$(echo ${{ github.ref }}|cut -d'/' -f 3)" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Loading the "base actions/checkout" so as to access the repository latexindent.pl
        uses: actions/checkout@v3
      - name: get latexindent announcement text from changelog.md
        id: announcement
        run: |
          egrep -i --color=auto '<!-- announcement:' documentation/changelog.md > tmp.log
          sed -i.bak s/\<\!\-\-\ announcement:\ // tmp.log
          sed -i.bak s/-\-\>// tmp.log
          echo "announcementtext=$(cat tmp.log)" >> $GITHUB_OUTPUT
      - name: download latexindent.zip
        uses: actions/download-artifact@master
        with:
          name: latexindent.zip
          path: for-ctan
      #
      # https://github.com/paolobrasolin/ctan-submit-action
      #
      - name: CTAN submit (validate only)
        uses: paolobrasolin/ctan-submit-action@v1
        with:
          action: validate
          file_path: for-ctan/latexindent.zip
          fields: |
            update: "true"
            pkg: latexindent
            version: "${{ steps.labeller.outputs.version }} ${{ steps.labeller.outputs.date }}"
            author: Chris Hughes
            email: christopher.michael.hughes@gmail.com 
            uploader: Chris Hughes
            announcement: "${{ steps.announcement.outputs.announcementtext}}, full details at https://github.com/cmhughes/latexindent.pl/releases/tag/${{ steps.labeller.outputs.version }}"
