name: Build and publish latexindent executables and documentation to releases
# PURPOSE:
#
#  1. build documentation latexindent.pdf 
#  2. build Windows latexindent.exe using PAR::Packer on Strawberry Perl, and publish to the most recent tag (release)
#  3. build Linux latexindent executable using PAR::Packer, and publish to the most recent tag (release)
#  4. build MacOS latexindent executable using PAR::Packer, and publish to the most recent tag (release)
#  5. create latexindent.zip, and publish latexindent.zip to the most recent tag (release)
#
# Note: this action only runs on *each release*, i.e. when tags are pushed
#

on:
  push:
    tags:
      - '*'

jobs:
  #=====================================================================================
  #
  # latexindent.zip
  #
  zip-files:
    name: 'create latexindent.zip and upload to release'
    runs-on: ubuntu-latest
    steps:
      - name: Loading the "base actions/checkout" so as to access the repository latexindent.pl
        uses: actions/checkout@v3
      - name: copy source files from repository into temporary folder
        run: |
          mkdir latexindent
          cp latexindent.pl latexindent/
          cp defaultSettings.yaml latexindent/
          mkdir latexindent/LatexIndent/
          cp LatexIndent/*.pm latexindent/LatexIndent/
          cp helper-scripts/latexindent-module-installer.pl latexindent/
          mkdir latexindent/bin/
      - name: copy documentation files from repository into temporary folder
        run: |
          mkdir latexindent/documentation/
          cp documentation/*.png latexindent/documentation/
          cp documentation/readme.txt latexindent/README
          cp documentation/*.json latexindent/documentation/
          cp documentation/*.bib latexindent/documentation/
          cd documentation
          egrep -i --color=auto '\\input' latexindent.tex > tmp.log 
          sed -i'.bak' -e 's/\\input{//' tmp.log
          sed -i'.bak' -e 's/}//' tmp.log
          awk '/sec-introduction/,EOF' tmp.log> tmp1.log
          mapfile -t filesToUpdate < tmp1.log
          sed -i.bak '/\\begin{document}/,$d' latexindent.tex
          echo '\begin{document}' >> latexindent.tex
          for file in "${filesToUpdate[@]}"; do cat ${file}.tex>>latexindent.tex; done
          echo '\end{document}' >> latexindent.tex
          cd ..
          cp documentation/latexindent.tex latexindent/documentation/
      - name: create latexindent.zip
        run: |
          zip -r latexindent.zip latexindent/
      - name: graphical representation of latexindent directory
        run: |
          find latexindent -print | sed -e 's;[^/]*/;|-- ;g;s;-- |; |;g'
      #
      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      #
      - name: upload latexindent.zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: latexindent.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "latexindent.pl release txt"
