name: Create and publish latexindent.exe and documentation latexindent.pdf to releases

on:
  push:
    tags:
      - '*'

jobs:
  build-latexindent-doc-pdf:
    name: 'latexindent.pdf documentation creation using arara on texlive'
    runs-on: ubuntu-latest
    steps:
      - name: Loading the "base actions/checkout" so as to access latexindent.pl
        uses: actions/checkout@v2
      - name: installing texlive full
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add openjdk11
            github_sha_short=$(echo $GITHUB_SHA | cut -c1-7)
            github_branch="main"
            github_release=$(echo ${{ github.ref }}|cut -d'/' -f 3)
            sed -i.bak s/\\\\gitAbbrevHash/$github_sha_short/ documentation/latexindent.tex
            sed -i.bak s/\\\\gitBranch/main/ documentation/latexindent.tex
            sed -i.bak s/\\\\gitRel/$github_release/ documentation/latexindent.tex
            sed -i.bak "s|\\\\gitAuthorDate|$(date +'%Y-%m-%d')|g" documentation/latexindent.tex
            cd documentation
            #######  arara -v latexindent.tex
            cp ../latexindent.pl latexindent.pdf
            cd ..
            mkdir -p target/release
            mv documentation/latexindent.pdf target/release
      # copy latexindent.pdf to the release
      #
      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      - uses: actions/upload-artifact@master
        with:
          name: latexindent.pdf
          path: target/release
  build-windows-exe:
    name: 'latexindent.exe creation using Strawberry Perl 5.32 on Windows'
    runs-on: 'windows-latest'
    steps:
      # checkout github.com/cmhughes/latexindent.pl
      #
      # https://github.com/actions/checkout
      - name: Loading the "base actions/checkout" so as to access latexindent.pl
        uses: actions/checkout@v2
      # install Strawberry Perl
      #
      # https://github.com/marketplace/actions/setup-perl-environment
      ###### - name: installing Perl
      ######   uses: shogo82148/actions-setup-perl@v1
      ######   with:
      ######     perl-version: '5.32'
      ######     distribution: strawberry
      # create latexindent.exe using Par::Packer
      #
      - name: creating latexindent.exe
        run: |
          ####### cpanm -f PAR::Packer
          ####### cpanm YAML::Tiny
          ####### cpanm File::HomeDir
          ####### cpanm Unicode::GCString
          copy helper-scripts/ppp.pl ./
          ####### perl ppp.pl -o latexindent.exe latexindent.pl
          cp latexindent.pl latexindent.exe
          mkdir -p target/release
          mv latexindent.exe target/release
      # upload latexindent.exe to the artifact
      #
      # https://stackoverflow.com/questions/57498605/github-actions-share-workspace-artifacts-between-jobs
      - uses: actions/upload-artifact@master
        with:
          name: latexindent.exe
          path: target/release
      # copy latexindent.exe to the release
      #
      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      - name: upload latexindent.exe to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/latexindent.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: "latexindent.pl release text"
  zip-files:
    name: 'Creating ctan.zip and uploading to release'
    needs: [build-latexindent-doc-pdf, build-windows-exe]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copying latexindent repository files to target/release
        run: |
          mkdir latexindent
          cp latexindent.pl latexindent/
          cp defaultSettings.yaml latexindent/
          cp -r LatexIndent latexindent/
          cp helper-scripts/latexindent-module-installer.pl latexindent/
          mkdir latexindent/documentation/
          cp documentation/*.tex latexindent/documentation/
          cp documentation/*.png latexindent/documentation/
          cp documentation/readme.txt latexindent/README
      - uses: actions/download-artifact@master
        with:
          name: latexindent.exe
          path: latexindent/
      - uses: actions/download-artifact@master
        with:
          name: latexindent.pdf
          path: latexindent/documentation/
      - uses: papeloto/action-zip@v1
        with:
          files: latexindent/
          dest: ctan.zip
      # copy latexindent.exe to the release
      #
      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      - name: upload ctan.zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ctan.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "latexindent.pl release text"
