name: Create and publish latexindent.exe and documentation latexindent.pdf to releases
# PURPOSE:
#
#  1. *create* latexindent.exe using PAR::Packer on Strawberry Perl
#  2. *publish* latexindent.exe to the most recent tag (release)
#  3. *create* latexindent.pdf 
#  4. *create* latexindent.zip
#  5. *publish* latexindent.zip to the most recent tag (release)
#
# Note: this action only runs on *each release*, i.e. when tags are pushed
#

on:
  push:
    tags:
      - '*'

jobs:
  build-latexindent-doc-pdf:
    name: 'latexindent.pdf documentation creation using arara on texlive'
    needs: [build-windows-exe]
    runs-on: ubuntu-latest
    steps:
      - name: load the "base actions/checkout" so as to access latexindent.pl
        uses: actions/checkout@v3
      - name: installing texlive full
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            github_sha_short=$(echo $GITHUB_SHA | cut -c1-7)
            github_branch="main"
            github_release=$(echo ${{ github.ref }}|cut -d'/' -f 3)
            sed -i.bak s/\\\\gitAbbrevHash/$github_sha_short/ documentation/latexindent.tex
            sed -i.bak s/\\\\gitBranch/main/ documentation/latexindent.tex
            sed -i.bak s/\\\\gitRel/$github_release/ documentation/*.tex
            sed -i.bak "s|\\\\gitAuthorDate|$(date +'%Y-%m-%d')|g" documentation/latexindent.tex
            cd documentation
            pdflatex --interaction=batchmode latexindent
            makeindex -s latexindent.ist -t latexindent.ilg latexindent.idx -o latexindent.ind
            bibtex latexindent
            pdflatex --interaction=batchmode latexindent
            pdflatex --interaction=batchmode latexindent
            pdflatex --interaction=batchmode latexindent
            cd ..
            mkdir -p target/release
            mv documentation/latexindent.pdf target/release
      #
      # https://stackoverflow.com/questions/57498605/github-actions-share-workspace-artifacts-between-jobs
      #
      - name: upload latexindent.pdf as artifact for zipping
        uses: actions/upload-artifact@master
        with:
          name: latexindent.pdf
          path: target/release
  build-windows-exe:
    name: 'latexindent.exe creation using Strawberry Perl 5.32 on Windows'
    runs-on: 'windows-latest'
    steps:
      #
      # checkout github.com/cmhughes/latexindent.pl
      # https://github.com/actions/checkout
      #
      - name: load the "base actions/checkout" so as to access latexindent.pl
        uses: actions/checkout@v3
      #
      # https://github.com/marketplace/actions/setup-perl-environment
      #
      - name: install Strawberry Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'
          distribution: strawberry
      - name: install Perl modules using cpan
        run: |
          wmic os get osarchitecture
          cpanm -f PAR::Packer
          cpanm YAML::Tiny
          cpanm File::HomeDir
          cpanm Unicode::GCString
      - name: preparations for PAR packer
        run: |
          sed -i'.bak' -r 's,eval\s\"use\sUnicode::GCString\"\sif\s\$switches\{GCString\},use Unicode::GCString,' latexindent.pl
          SET PAR_VERBATIM=1
      #
      # https://metacpan.org/pod/pp
      # https://github.com/plk/biber/blob/dev/dist/MSWIN64/build.bat
      #
      - name: create latexindent.exe using PAR Packer
        run: >-
          pp 
          --addfile="defaultSettings.yaml;lib/LatexIndent/defaultSettings.yaml"
          --cachedeps=scancache
          --output latexindent.exe
          latexindent.pl
      - name: move latexindent.exe to release directory
        run: |
          mkdir -p target/release
          mv latexindent.exe target/release
      - name: tiny test of latexindent.exe from release directory
        run: |
          cd target/release 
          ./latexindent.exe --help
          ./latexindent.exe ../../test-cases/environments/environments-simple-nested.tex
      #
      # https://stackoverflow.com/questions/57498605/github-actions-share-workspace-artifacts-between-jobs
      #
      - name: upload latexindent.exe as artifact for zipping
        uses: actions/upload-artifact@master
        with:
          name: latexindent.exe
          path: target/release
      #
      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      #
      - name: upload latexindent.exe to release page
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/latexindent.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: "latexindent.pl release text"
  build-linux-executable:
    name: 'create linux executable latexindent'
    runs-on: 'ubuntu-latest'
    steps:
      #
      # checkout github.com/cmhughes/latexindent.pl
      # https://github.com/actions/checkout
      #
      - name: load the "base actions/checkout" so as to access latexindent.pl
        uses: actions/checkout@v3
      #
      # https://github.com/marketplace/actions/setup-perl-environment
      #
      - name: install Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'
      - name: install Perl modules using cpan
        run: |
          cpanm -f PAR::Packer
          cpanm YAML::Tiny
          cpanm File::HomeDir
          cpanm Unicode::GCString
      - name: preparations for PAR packer
        run: |
          sed -i'.bak' -r 's,eval\s\"use\sUnicode::GCString\"\sif\s\$switches\{GCString\},use Unicode::GCString,' latexindent.pl
          SET PAR_VERBATIM=1
      #
      # https://metacpan.org/pod/pp
      # https://github.com/plk/biber/blob/dev/dist/MSWIN64/build.bat
      #
      - name: create linux executable latexindent using PAR Packer
        run: >-
          pp 
          --addfile="defaultSettings.yaml;lib/LatexIndent/defaultSettings.yaml"
          --cachedeps=scancache
          --output latexindent-linux
          latexindent.pl
      - name: move linux latexindent to release directory
        run: |
          mkdir -p target/release
          mv latexindent-linux target/release
      - name: tiny test of latexindent from release directory
        run: |
          cd target/release 
          ./latexindent-linux --help
          ./latexindent-linux ../../test-cases/environments/environments-simple-nested.tex
      #
      # https://stackoverflow.com/questions/57498605/github-actions-share-workspace-artifacts-between-jobs
      #
      - name: upload latexindent-linux as artifact for zipping
        uses: actions/upload-artifact@master
        with:
          name: latexindent-linux
          path: target/release
  zip-files:
    name: 'Creating latexindent.zip and uploading to release'
    needs: [build-latexindent-doc-pdf, build-windows-exe, build-linux-executable]
    runs-on: ubuntu-latest
    steps:
      - name: Loading the "base actions/checkout" so as to access the repository latexindent.pl
        uses: actions/checkout@v3
      - name: copy source files from repository into temporary folder
        run: |
          mkdir latexindent
          cp latexindent.pl latexindent/
          cp defaultSettings.yaml latexindent/
          mkdir latexindent/LatexIndent/
          cp LatexIndent/*.pm latexindent/LatexIndent/
          cp helper-scripts/latexindent-module-installer.pl latexindent/
          mkdir latexindent/latexindent-windows
          mkdir latexindent/latexindent-linux
      - name: copy documentation files from repository into temporary folder
        run: |
          mkdir latexindent/documentation/
          cp documentation/*.tex latexindent/documentation/
          cp documentation/*.png latexindent/documentation/
          cp documentation/readme.txt latexindent/README
          cp documentation/*.json latexindent/documentation/
      - name: download latexindent.exe
        uses: actions/download-artifact@master
        with:
          name: latexindent.exe
          path: latexindent/latexindent-windows
      - name: download linux executable latexindent 
        uses: actions/download-artifact@master
        with:
          name: latexindent-linux
          path: latexindent/latexindent-linux
      - name: download latexindent.pdf
        uses: actions/download-artifact@master
        with:
          name: latexindent.pdf
          path: latexindent/documentation/
      - name: create latexindent.zip
        run: |
          mv latexindent/latexindent-linux/latexindent-linux latexindent/latexindent-linux/latexindent
          zip -r latexindent.zip latexindent/
      - name: graphical representation of latexindent directory
        run: |
          find latexindent -print | sed -e 's;[^/]*/;|-- ;g;s;-- |; |;g'
      #
      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      #
      - name: upload latexindent.zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: latexindent.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "latexindent.pl release text"
