name: ctan upload
# PURPOSE:
#
#  1. *create* latexindent.exe using PAR::Packer on Strawberry Perl
#  2. *publish* latexindent.exe to the most recent tag (release)
#  3. *create* latexindent.pdf 
#  4. *create* latexindent.zip
#  5. *publish* latexindent.zip to the most recent tag (release)
#
# Note: this action only runs on *each release*, i.e. when tags are pushed
#

on:
  push:
    tags:
      - '*'

jobs:
  #
  # dummy routine to simulate latexindent.zip
  #
  build-latexindent-zip:
    name: 'build latexindent.zip'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: create latexindent.zip
        run: |
          mkdir latexindent
          mkdir latexindent/documentation
          cp readme.md latexindent/README
          cp readme.md latexindent/documentation/cmh-documentation.pdf
          cp -r LatexIndent/*.pm latexindent/
          zip -r latexindent.zip latexindent
          mkdir -p target/release
          mv latexindent.zip target/release
      - name: upload latexindent.zip as artifact
        uses: actions/upload-artifact@master
        with:
          name: latexindent.zip
          path: target/release
      - name: get changelog.md information
        id: changelog
        run: |
          csplit documentation/changelog.md '/^\#\#/' '{*}' -f cmh
          sed -i.bak s/\#\#.*\// cmh01
      - name: upload latexindent.zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/latexindent.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: cat cmh01
  #
  # ctan latexindent.zip upload
  #
  ctan-upload:
    name: 'upload latexindent.zip to ctan'
    runs-on: ubuntu-latest
    needs: [build-latexindent-zip]
    steps:
      - name: get latexindent version number
        id: labeller
        run: |
          echo "version=$(echo ${{ github.ref }}|cut -d'/' -f 3)" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: get latexindent announcement text
        id: announcement
        run: |
          egrep -i --color=auto '<!-- announcement:' documentation/changelog.md > tmp.log
          sed -i.bak s/\<\!\-\-\ announcement:\ // tmp.log
          sed -i.bak s/-\-\>// tmp.log
          echo "announcementtext=$(cat tmp.log)" >> $GITHUB_OUTPUT
      - name: download latexindent.zip
        uses: actions/download-artifact@master
        with:
          name: latexindent.zip
          path: for-ctan
      - name: CTAN submit (validate only)
        uses: paolobrasolin/ctan-submit-action@v1
        with:
          action: validate
          file_path: for-ctan/latexindent.zip
          fields: |
            update: "true"
            pkg: latexindent
            version: "${{ steps.labeller.outputs.version }} ${{ steps.labeller.outputs.date }}"
            author: Chris Hughes
            email: christopher.michael.hughes@gmail.com 
            uploader: Chris Hughes
            announcement: "${{ steps.announcement.outputs.announcementtext}}, full details at https://github.com/cmhughes/latexindent.pl/releases/tag/${{ steps.labeller.outputs.version }}"
