name: build documentation

on:
  push:
    tags:
      - '*'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add default-jre
            arara documentation/latexindent.tex
