name: build documentation

on:
  push:
    tags:
      - '*'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Loading the "base actions/checkout" so as to access latexindent.pl
        uses: actions/checkout@v2
      - name: update Git information for gitinfo2 package
        run: |
          cd documentation
          # https://stackoverflow.com/questions/58886293/getting-current-branch-and-commit-hash-in-github-action
          github_sha_short=$(echo $GITHUB_SHA | cut -c1-7)
          github_branch="main"
          github_release=$(echo ${{ github.ref }}|cut -d'/' -f 3)
          release_date=$(date --rfc-3339=date)
          sed -i.bak  s/usepackage\\[mark,grumpy\\]{gitinfo2}/usepackage[mark]{gitinfo2}/ latexindent.tex
          sed -i.bak s/\\\\gitAbbrevHash/$github_sha_short/ latexindent.tex
          sed -i.bak s/\\\\gitBranch/main/ latexindent.tex
          sed -i.bak s/\\\\gitRel/$github_release/ latexindent.tex
          sed -i.bak s/\\\\gitAuthorDate/$release_date/ latexindent.tex
          cat latexindent.tex

#jobs:
#  build_latex:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Loading the "base actions/checkout" so as to access latexindent.pl
#        uses: actions/checkout@v2
#      - name: installing texlive full
#        uses: xu-cheng/texlive-action/full@v1
#        with:
#          run: |
#            apk add openjdk11
#            cd documentation
#            $(echo $GITHUB_REF)
#            branch_name=$(echo $GITHUB_REF | cut -d'/' -f 3)
#            github_sha_short=$(echo $GITHUB_SHA | cut -c1-7)
#            sed -i.bak  s/usepackage\\[mark,grumpy\\]{gitinfo2}/usepackage[mark]{gitinfo2}/ latexindent.tex
#            sed -i.bak s/\\\\gitAbbrevHash/$github_sha_short/ latexindent.tex
#            sed -i.bak s/\\\\gitBranch/$branch_name/ latexindent.tex
#            cat latexindent.tex
#            arara -v latexindent.tex
