name: Windows executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: 'windows-latest'
    name: 'Perl 5.32 on Windows'
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'
          distribution: strawberry
      - run: |
          cpanm -f PAR::Packer
          pp -o cmh.exe hello-world.pl
