name: latexindent.pl run test-cases/test-cases.sh if key files changed
on:
  pull_request:
    branches:
      - main

jobs:
  check-pm-files-changed:
    name: latexindent.pl check if latexindent.pl, defaultSettings.yaml, .pm files changed
    runs-on: ubuntu-latest
    outputs:
      anychanged: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get changed files, latexindent.pl
        id: changed-files
        uses: tj-actions/changed-files@v23.1
        with:
          since_last_remote_commit: "true"
          use_fork_point: "true"
          files: |
            latexindent.pl
            defaultSettings.yaml
            LatexIndent/*.pm
      - if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        name: List all relevant changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file has changed compared to main branch"
          done
      - if: ${{ steps.changed-files.outputs.any_changed == 'false' }}
        name: No perl based files have changed
        run: |
            echo ""
            echo "none of latexindent.pl, defaultSettings.yaml, LatexIndent/*.pm have changed since last commit"
            echo "no need to run the rest of batch-check.yaml :)"
            echo ""
