name: latexindent.pl run test-cases/test-cases.sh if key files changed
# PURPOSE:
#
#   (1) check that at least one of
#
#           latexindent.pl
#           defaultSettings.yaml
#           LatexIndent/*.pm
#
#       have been changed since the last commit
#
#   (2) if so, then run 
#
#           test-cases/test-cases.sh 
#
#       and check for changes; report the results
#
# Note: 
#       
#       this action runs only on DEVELOP branch
#
  
on:
  pull_request_target:
    branches:
      - main

jobs:
  check-test-cases-files-changed:
    #
    # check if any key files have changed
    #
    # reference: 
    #            https://github.com/jbranchaud/til/blob/master/github-actions/capture-an-output-value-for-use-in-a-later-step.md
    #            https://stackoverflow.com/questions/67368005/check-whether-environment-variable-is-empty
    #            https://docs.github.com/en/actions/learn-github-actions/expressions
    #            https://www.integralist.co.uk/posts/github-actions/#terminology
    #
    runs-on: ubuntu-latest
    steps:
      - name: Loading the "base actions/checkout" so as to access latexindent.pl
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check for changed pm files, latexindent.pl, defaultSettings.yaml
        id: changed-files
        run: |-
          fileschanged=$(git diff --name-only main|grep -E 'LatexIndent|defaultSettings|latexindent.pl')
          if [ "$fileschanged" == "" ]; then
            echo ::set-output name=testcaseneeded::false
          else
            echo ::set-output name=testcaseneeded::true
          fi
      - if: ${{ steps.changed-files.outputs.testcaseneeded == 'true' }}
        name: List all relevant changed files
        run: |
            echo "files changed since last commit"
            git diff --name-only main|grep -E 'LatexIndent|defaultSettings|latexindent.pl'
      - if: ${{ steps.changed-files.outputs.testcaseneeded == 'false' }}
        name: No perl based files have changed
        run: |
            echo ""
            echo "none of latexindent.pl, defaultSettings.yaml, LatexIndent/*.pm have changed since last commit"
            echo "no need to run any test-cases :)"
            echo ""
  latexindent-test-cases:
    needs: check-test-cases-files-changed
    if: ${{fromJSON(needs.check-test-cases-files-changed.steps.changed-files.outputs.testcaseneeded)}}
    runs-on: ubuntu-latest
    name: test-cases.sh check as perl related files changed
    steps:
      # install Perl
      #
      # https://github.com/marketplace/actions/setup-perl-environment
      - name: installing Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: 5.34
      - name: installing perl modules for latexindent.pl
        run: |
          cpanm YAML::Tiny
          cpanm File::HomeDir
      # checkout github.com/cmhughes/latexindent.pl
      #
      # https://github.com/actions/checkout
      - name: Loading the "base actions/checkout" so as to access latexindent.pl
        uses: actions/checkout@v3
      - name: run test-cases/test-cases.sh
        shell: bash
        run: |
          chmod +x latexindent.pl
          cp latexindent.pl /usr/local/bin
          cp -r LatexIndent /usr/local/bin
          cp defaultSettings.yaml /usr/local/bin
          cd test-cases/
          ./test-cases.sh
      - name: Check for changed files in test-cases
        uses: tj-actions/changed-files@v23
        id: changed-files
        with:
          files: |
            test-cases/
      - if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        name: List all changed files from test-cases
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file has changed on this pull request"
          done
      - if: ${{ steps.changed-files.outputs.any_changed == 'false' }}
        name: No test-cases files have changed
        run: |
            echo ""
            echo "none of test-cases have changed on this pull request,"
            echo "full review still needed, but this is a good sign :)"
            echo ""
